### ISSUE TITLE
Refactor ci to use node install buildin cache

### ISSUE THREAD

**Issue by viceice** [renovatebot/pep440#114]
**What would you like to be able to do?**

We should use the node install action buildin cache like in other repos

**Did you already have any implementation ideas?**

Use same code as in other repo's

**Comment by RahulGautamSingh** [comment]
Hey @viceice , I would like to take this one, if it's okay.

**Comment by RahulGautamSingh** [comment]
@viceice Seems to me that this addition should do the job.
```
- name: Cache node_modules
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
        with:
          path: node_modules
          key: ${{ env.YARN_MODULES_CACHE_KEY }}-${{ runner.os }}-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.YARN_MODULES_CACHE_KEY }}-${{ runner.os }}-${{ env.NODE_VERSION }}-yarn-
```

**Comment by viceice** [comment]
no. Something like this:

```yaml


      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
```
